### Get all data stored in auth table

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ali@example.com",
  "password": "password123"
}

### Get a user token
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJBbGkgS2hhbiIsImVtYWlsIjoiYWxpQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYzMjQ5NzUwLCJleHAiOjE3NjMzMzYxNTB9.b1bsMFhGism-r_FqdJYNy9WflN1ImPFocck1g2JUGFs

### Register a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name":"Asad Irfan",
  "email":"asad@example.com",
  "password":"password123"
}