### GET ALL USERS
GET http://localhost:3000/users

### CREATE A USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Asad Irfan",
    "email":"asadirfan8t@gmail.com",
    "passwordHash":"asad123"
}

### Get users task by Id
GET http://localhost:3000/users/1/tasks