### Get all user-habits
GET http://localhost:3000/user-habits


### Assign a new habit to a user
POST http://localhost:3000/user-habits
Content-Type: application/json

{
    "userId":1,
    "habitId":4
}

### GET all habits assigned to a user
GET http://localhost:3000/user-habits/user/1
